// src/app/layout.tsx
"use client"; // Mark this as a client component so we can use useState, context, etc.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import your provider
import { AppStateProvider } from "@/lib/AppStateProvider"; 
// or wherever you placed the file

import BackButton from "@/components/BackButton"; 
import SettingsModal from "@/components/SettingsModal"; // your Next.js version of the modal

import { FiSettings } from "react-icons/fi"; // Icon from react-icons (npm install react-icons)
import React, { useState } from "react";
import Image from "next/image";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Remove or move this export to a non-client component file
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);

  const pathname = usePathname();
  const isHomePage = pathname === "/"; // Determine if we're on the homepage using the pathname

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppStateProvider>
          {/* Conditionally render the logo or back button with the original styling */}
          <div className="fixed top-4 left-4 p-2 bg-black rounded-full transition-all shadow-md z-30">
            {isHomePage ? (
              <Image 
                src="/assets/images/CM_logo.png"
                width={32}
                height={32}
                alt="CM Logo"
              />
            ) : (
              <BackButton />
            )}
          </div>

          <div style={{ position: 'fixed', top: '1.5rem', right: '1rem', zIndex: 1000 }}>
            <button
              style={{
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                color: 'white',
              }}
              onClick={() => setIsSettingsOpen(true)}
              aria-label="Open Settings"
            >
              <FiSettings size={30} />
            </button>
          </div>
          {/* Main page content */}
          {children}

          {/* Settings Modal (only visible if isSettingsOpen is true) */}
          <SettingsModal
            visible={isSettingsOpen}
            onClose={() => setIsSettingsOpen(false)}
          />

          {/* Inline styling for quick demo; 
              replace with your own CSS or a CSS module if you prefer */}
          <style jsx>{`
            .settingsIcon {
              background: none;
              border: none;
              cursor: pointer;
              color: white;
            }
            .settingsIcon:hover {
              color: #ccc;
            }
          `}</style>
        </AppStateProvider>
      </body>
    </html>
  );
}
